# Generated by Django 2.1.3 on 2018-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador', models.CharField(help_text='nome completo', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('raca', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
                ('vacinas', models.BooleanField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Tipo do Aminal', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='pessoa',
        ),
        migrations.AddField(
            model_name='animais',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.Tipo'),
        ),
    ]
